# Generated by Django 6.0.6 on 2026-06-11 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_avatar_alter_studentprofile_avatar_avatarlevelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerfulFoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.PositiveIntegerField(help_text='HP base do inimigo. Mana necessário = hp * número de alunos da guilda')),
                ('image', models.ImageField(blank=True, upload_to='foes/')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(help_text='Ordem de aparição (menor = enfrentado primeiro)', unique=True)),
            ],
            options={
                'verbose_name': 'Poderoso Inimigo',
                'verbose_name_plural': 'Poderosos Inimigos',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('join_code', models.SlugField(help_text='Código para alunos entrarem na guilda', max_length=10, unique=True)),
                ('head_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headed_guilds', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Guilda',
                'verbose_name_plural': 'Guildas',
            },
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='classes.guild')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_memberships', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Membro da Guilda',
                'verbose_name_plural': 'Membros da Guilda',
                'unique_together': {('student', 'guild')},
            },
        ),
        migrations.CreateModel(
            name='GuildFoeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defeated', models.BooleanField(default=False)),
                ('defeated_at', models.DateTimeField(blank=True, null=True)),
                ('total_mana_contributed', models.PositiveIntegerField(default=0)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foe_progresses', to='classes.guild')),
                ('foe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_progresses', to='classes.powerfulfoe')),
            ],
            options={
                'verbose_name': 'Progresso contra Inimigo',
                'verbose_name_plural': 'Progressos contra Inimigos',
                'unique_together': {('guild', 'foe')},
            },
        ),
    ]
