# Generated by Django 6.0.6 on 2026-06-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('content', '0006_alter_badge_condition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerfulfoe',
            name='badge',
            field=models.ForeignKey(blank=True, help_text='Distintivo concedido a todos os membros ao derrotar este inimigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerful_foes', to='content.badge'),
        ),
    ]
