# Generated by Django 6.0.6 on 2026-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_avatar_alter_studentprofile_avatar_avatarlevelimage'),
        ('classes', '0002_powerfulfoe_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se falso, a guilda não aparece no painel do professor'),
        ),
        migrations.AddField(
            model_name='guild',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Professores associados a esta guilda (além do head teacher)', related_name='guilds', to='accounts.teacherprofile'),
        ),
    ]
