# Generated by Django 6.0.6 on 2026-06-11 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatares',
            },
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='accounts.avatar'),
        ),
        migrations.CreateModel(
            name='AvatarLevelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='avatars/')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.avatar')),
            ],
            options={
                'verbose_name': 'Imagem de Avatar por Nível',
                'verbose_name_plural': 'Imagens de Avatar por Nível',
                'ordering': ('avatar', 'level'),
                'unique_together': {('avatar', 'level')},
            },
        ),
    ]
