# Generated by Django 6.0.6 on 2026-06-11 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('pillar', models.CharField(choices=[('decomposition', 'Decomposição'), ('patterns', 'Reconhecimento de Padrões'), ('abstraction', 'Abstração'), ('algorithms', 'Algoritmos')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('story_text', models.TextField(blank=True)),
                ('learning_goal', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='easy', max_length=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('mana_reward', models.PositiveIntegerField(default=10)),
                ('is_published', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='content.module')),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('module', 'order')},
            },
        ),
    ]
