# Generated by Django 6.0.6 on 2026-06-11 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_avatar_alter_studentprofile_avatar_avatarlevelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='badges/')),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('grimoire_complete', 'Completar um Grimório'), ('spell_complete', 'Completar um Feitiço'), ('spell_count', 'Completar N feitiços'), ('hard_spell_complete', 'Completar um feitiço difícil'), ('level_reached', 'Alcançar nível N'), ('mana_reached', 'Acumular N de mana')], max_length=30)),
                ('condition_value', models.CharField(help_text='Valor específico para a condição (ex: ID do grimório, número de feitiços, nível)', max_length=100)),
            ],
            options={
                'verbose_name': 'Distintivo',
                'verbose_name_plural': 'Distintivos',
            },
        ),
        migrations.CreateModel(
            name='Grimoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('text_content', models.TextField(help_text='Conteúdo teórico do grimório')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('mana_reward', models.PositiveIntegerField(default=50, help_text='Mana extra concedida ao completar todos os feitiços')),
                ('badge', models.ForeignKey(blank=True, help_text='Distintivo concedido ao completar este grimório', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grimoires', to='content.badge')),
            ],
            options={
                'verbose_name': 'Grimório',
                'verbose_name_plural': 'Grimórios',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enunciado do problema')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='easy', max_length=10)),
                ('mana_reward', models.PositiveIntegerField(editable=False)),
                ('order', models.PositiveIntegerField()),
                ('validation_data', models.JSONField(blank=True, help_text='Dados para validação da solução (ex: blocos esperados, saída esperada)', null=True)),
                ('badge', models.ForeignKey(blank=True, help_text='Distintivo concedido ao completar este feitiço', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spells', to='content.badge')),
                ('grimoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='content.grimoire')),
            ],
            options={
                'verbose_name': 'Feitiço',
                'verbose_name_plural': 'Feitiços',
                'ordering': ('grimoire', 'order'),
                'unique_together': {('grimoire', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SpellCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_submitted', models.TextField(blank=True, help_text='Código Blockly submetido')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='content.spell')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_completions', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Feitiço Completado',
                'verbose_name_plural': 'Feitiços Completados',
                'unique_together': {('student', 'spell')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Slot 1'), (2, 'Slot 2'), (3, 'Slot 3')], help_text='Posição de exibição no perfil (1-3). Deixe vazio para não exibir.', null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='content.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Distintivo do Aluno',
                'verbose_name_plural': 'Distintivos do Aluno',
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
