# Generated by Django 6.0.6 on 2026-06-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grimoire',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Grimórios que devem ser completados antes deste', to='content.grimoire'),
        ),
    ]
