# Generated by Django 6.0.6 on 2026-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_grimoire_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='grimoire',
            name='icon',
            field=models.CharField(default='book', help_text='Nome do ícone Lucide para representar este grimório', max_length=50),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Se desligado, o feitiço é opcional e não precisa ser completado para finalizar o grimório'),
        ),
    ]
