# Generated by Django 6.0.6 on 2026-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_grimoire_icon_spell_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='blockly_toolbox',
            field=models.JSONField(blank=True, help_text='Configuração JSON da toolbox do Blockly (categorias e blocos)', null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Saída esperada para validação da solução'),
        ),
        migrations.AddField(
            model_name='spell',
            name='required_block_types',
            field=models.JSONField(blank=True, help_text='Lista de tipos de bloco Blockly obrigatórios na solução', null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='tip',
            field=models.TextField(blank=True, help_text='Dica opcional para ajudar o estudante a resolver o feitiço'),
        ),
        migrations.AddField(
            model_name='spellcompletion',
            name='tip_used',
            field=models.BooleanField(default=False),
        ),
    ]
