# Generated by Django 6.0.6 on 2026-06-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_spell_blockly_toolbox_spell_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='alternative_block_types',
            field=models.JSONField(blank=True, help_text='Lista de grupos de tipos de bloco alternativos. Cada grupo é uma lista — pelo menos um bloco de cada grupo deve estar presente.', null=True),
        ),
    ]
