# Generated by Django 6.0.6 on 2026-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_spell_alternative_block_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('grimoire_complete', 'Completar um Grimório'), ('spell_complete', 'Completar um Feitiço'), ('spell_count', 'Completar N feitiços'), ('hard_spell_complete', 'Completar um feitiço difícil'), ('level_reached', 'Alcançar nível N'), ('mana_reached', 'Acumular N de mana'), ('foe_defeated', 'Derrotar um inimigo poderoso')], max_length=30),
        ),
    ]
